# Generated by Django 4.0 on 2022-01-16 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_alter_groups_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('a923a3d9-2c16-45ed-9a59-cb33b98b06cb'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('repo_link', models.CharField(blank=True, max_length=256)),
                ('included_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('e5845259-33b2-466e-9a9e-704c415b4731'), primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=32)),
                ('inner_text', models.TextField(blank=True)),
                ('Дата', models.DateField(verbose_name='Дата выполнения')),
                ('is_complited', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notesapp.project')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
