# Generated by Django 4.0 on 2022-01-19 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0007_alter_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('6035b5c2-b5ca-4a1f-8edc-2d8ddb3bd088'), primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('repo_link', models.CharField(blank=True, max_length=256)),
                ('included_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('a39192b3-8a5c-46dd-a8d8-c1a058924e69'), primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=48)),
                ('inner_text', models.TextField(blank=True)),
                ('Дата', models.DateField(verbose_name='Дата выполнения')),
                ('is_complited', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notesapp.project')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
