# Generated by Django 4.0 on 2022-01-19 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5c391d2e-66a2-4781-a922-4e82cc2fd9d5'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4e6a25e9-47a4-4850-9369-43cb5c7d57c5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
