# Generated by Django 4.0 on 2022-02-02 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 2, 2), verbose_name='Completion date'),
        ),
    ]
