# Generated by Django 4.0 on 2022-01-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_alter_notes_uuid_alter_project_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
