# Generated by Django 4.0 on 2022-02-13 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_alter_notes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Date',
            field=models.DateField(default=datetime.date(2022, 2, 13), verbose_name='Completion date'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='project_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notesapp.project'),
        ),
    ]
