# Generated by Django 4.0 on 2022-01-19 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_alter_notes_uuid_alter_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
