# Generated by Django 4.0 on 2022-02-13 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_alter_notes_date_alter_notes_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notesapp.project'),
        ),
    ]
