# Generated by Django 4.0 on 2022-01-19 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_groups_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3bcaae3a-eb96-4795-9f98-a3796f66f6b4'), primary_key=True, serialize=False),
        ),
    ]
