# Generated by Django 4.0 on 2022-01-19 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('761b76aa-02f3-41ea-8e2d-449e8304b002'), primary_key=True, serialize=False),
        ),
    ]
