# Generated by Django 4.0 on 2022-01-19 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bab0e5bd-a882-424d-b44e-b401b4082c18'), primary_key=True, serialize=False),
        ),
    ]
