# Generated by Django 4.0 on 2022-01-19 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0d41f0c0-b8e2-41af-9c91-096316010589'), primary_key=True, serialize=False),
        ),
    ]
