# Generated by Django 4.0 on 2022-01-19 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dce6fafa-9280-419d-8ec1-e1dcce3554e2'), primary_key=True, serialize=False),
        ),
    ]
