# Generated by Django 4.0 on 2022-01-19 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a02a4644-06db-4c43-956e-bfe1e35bd5e3'), primary_key=True, serialize=False),
        ),
    ]
