# Generated by Django 4.0 on 2022-01-16 16:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('378fbc87-ec1e-4ed8-aad9-f8275b26b96e'), primary_key=True, serialize=False),
        ),
    ]
