# Generated by Django 4.0 on 2022-01-19 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ffcca7c4-98db-4464-9210-57f9c37964b0'), primary_key=True, serialize=False),
        ),
    ]
