# Generated by Django 4.0 on 2022-01-19 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2b28a5f2-764c-4f7a-b954-9ea907341946'), primary_key=True, serialize=False),
        ),
    ]
