# Generated by Django 4.0 on 2022-01-19 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('880205af-d394-47f5-b2cb-78d4d9eb8190'), primary_key=True, serialize=False),
        ),
    ]
