# Generated by Django 4.0 on 2022-01-19 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('44634b1d-3752-4e51-a72d-754f51281c74'), primary_key=True, serialize=False),
        ),
    ]
