# Generated by Django 4.0 on 2022-01-19 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('179e13a0-e828-433a-a041-497d3ca4d2cd'), primary_key=True, serialize=False),
        ),
    ]
