# Generated by Django 4.0 on 2022-01-19 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c527a9ac-459b-4819-b4a5-f8acdda333ac'), primary_key=True, serialize=False),
        ),
    ]
