# Generated by Django 4.0 on 2022-01-19 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c0e3905-51fc-4974-aabe-93db746da1a6'), primary_key=True, serialize=False),
        ),
    ]
