# Generated by Django 4.0 on 2022-01-19 19:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0009_alter_author_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('60644741-9158-43ba-8683-c9ef3843dc55'), primary_key=True, serialize=False),
        ),
    ]
